### ISSUE TITLE
Incompatibility with last cmigemo

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-jp/migemo#21]
It seems that migemo.el doesn't accept the "-w" switch of cmigemo.

The "-w" switch should appear at end of command, unfortunately, `migemo-init` is appending the
`migemo-options` on top of the `migemo-dictionary` settings.

I add to modify `migemo-init` like this:

```diff
diff --git a/migemo.el b/migemo.el
index ccfe1ae..fe0ab33 100755
--- a/migemo.el
+++ b/migemo.el
@@ -221,14 +221,14 @@
 	   (eq (process-status migemo-process) 'run))
       (let ((options
 	     (delq nil
-		   (append migemo-options
-			   (when (and migemo-user-dictionary
+		   (append (when (and migemo-user-dictionary
 				      (file-exists-p migemo-user-dictionary))
 			     (list "-u" migemo-user-dictionary))
 			   (when (and migemo-regex-dictionary
 				      (file-exists-p migemo-regex-dictionary))
 			     (list "-r" migemo-regex-dictionary))
-			   (list "-d" migemo-dictionary)))))
+			   (list "-d" migemo-dictionary)
+                           migemo-options))))
 	(setq migemo-buffer (get-buffer-create " *migemo*"))
 	(setq migemo-process (migemo-start-process
 			      "migemo" migemo-buffer migemo-command options))


```

**Comment by syohex** [comment]
> The "-w" switch should appear at end of command

https://github.com/koron/cmigemo/blob/3962d7ba10c5dfe9f57d60ff69994c15ab68c69e/src/main.c#L95-L112

It seems that `-w` option is treated same as other options and its order is not unrelated to the issue.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

>     The "-w" switch should appear at end of command
>    
> https://github.com/koron/cmigemo/blob/3962d7ba10c5dfe9f57d60ff69994c15ab68c69e/src/main.c#L95-L112
>
> It seems that -w option is treated same as other options and its order is not unrelated to the issue.

Here what happen from the command line when running cmigemo on "foo":

thierry@dell-14z:~/elisp/helm$ cmigemo -q -e -n -w -d /usr/share/cmigemo/utf-8/migemo-dict foo
-d
thierry@dell-14z:~/elisp/helm$ cmigemo -q -e -n -d /usr/share/cmigemo/utf-8/migemo-dict -w foo
\(¶\|ふぉお\|ｆｏｏ\|フ\(ォオ\|ッ[タト]\|ー[ルズド]\)\|foo\)

As you can see the -w option should be passed just before pattern (foo).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by syohex** [comment]
> thierry@dell-14z:~/elisp/helm$ cmigemo -q -e -n -w -d /usr/share/cmigemo/utf-8/migemo-dict foo -d thierry@dell-14z:~/elisp/helm$ cmigemo -q -e -n -d /usr/share/cmigemo/utf-8/migemo-dict -w foo \(¶\|ふぉお\|ｆｏｏ\|フ\(ォオ\|ッ[タト]\|ー[ルズド]\)\|foo\)

`-w` option takes an argument. So you should write 

```
% cmigemo -q -e -n -w foo -d dictionary_path
```

And `migemo-init` launch cmigemo with interactive mode, so we should not set `-w` option to `migemo-options`. `-w` means non-interactive mode.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> -w option takes an argument. So you should write
>
> % cmigemo -q -e -n -w foo -d dictionary_path

Sure but in migemo.el, the function migemo-get-pattern is using 

(process-send-string migemo-process (concat word "\n"))

so the command line would look like this:

% cmigemo -q -e -n -w -d dictionary_path foo

which doesn't work of course.

With the patch I sent it ensure the options are after the
directory_path:

% cmigemo -q -e -n -d dictionary_path -w foo

> And migemo-init launch cmigemo with interactive mode, so we should not
> set -w option to migemo-options. -w means non-interactive mode.

Right, but the -w option is needed later when sendind string to process
in migemo-get-pattern.

PS: the goal is to make migemo working in helm, see

https://github.com/emacs-helm/helm/pull/1174

so I need of course a working migemo.el to achieve this.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by syohex** [comment]
> Sure but in migemo.el, the function migemo-get-pattern is using
>
> (process-send-string migemo-process (concat word "\n"))
>
> so the command line would look like this:
>
> % cmigemo -q -e -n -w -d dictionary_path foo which doesn't work of course.
>

No. It is like this. `-w` is not necessary.

```
% echo foo | cmigemo -q -e -n -d ./dict/utf-8.d/migemo-dict
\(¶\|ﾌｫｵ\|ふぉお\|ｆｏｏ\|フ\(ォオ\|ッ[タト]\|ー[ルズド]\)\|foo\)
```

`process-send-string` sends string to `process`'s input(STDIN), not command line argument.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

>     Sure but in migemo.el, the function migemo-get-pattern is using
>    
>     (process-send-string migemo-process (concat word "\n"))
>    
>     so the command line would look like this:
>    
>     % cmigemo -q -e -n -w -d dictionary_path foo which doesn't work of course.
>    
> No. It is like this. -w is not necessary.

As you want, but migemo is not working at all here without "-w" option.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syohex** [comment]
https://github.com/emacs-helm/helm/pull/1174 can work with current migemo.el

![output](https://cloud.githubusercontent.com/assets/554281/9956486/0fb3a564-5e34-11e5-8bb5-ac9e0bb104d4.gif)

Configuration is here. `-w` is not used.

```lisp
(require 'migemo)
(setq migemo-command "cmigemo")
(setq migemo-options '("-q" "--emacs"))

;; Set your installed path
(setq migemo-dictionary "/usr/local/share/migemo/utf-8/migemo-dict")

(setq migemo-user-dictionary nil)
(setq migemo-regex-dictionary nil)
(setq migemo-coding-system 'utf-8-unix)
(migemo-init)
```

Sorry I don't understand why migemo.el should apply your change.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> emacs-helm/helm#1174 can work with current migemo.el
>
> output  

Glad it is working :-)

Could you try also with helm-occur and helm kill ring ?

> Configuration is here. -w is not used.

I tried this configuration but it doesn't work for me.
I guess the version of cmigemo works differently here,
without -w flag, I can'y make it working even on the command line.

But if it works for you great, I wont use this once it will be fixed in
helm.

> Sorry I don't understand why migemo.el should apply your change.

The change proposed should not affect your usage of migemo, it change
nothing, it just pass -d option before others instead of after.
But I wanted to ask you before, it is why I didn't send a PR.

The point is to clarify why one version of cmigemo needs the -w option and
the other don't.

Or perhaps I missed something.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
You are right, I finally could get it working without "-w" option after reinstalling all.
So I am closing now.

Thanks for your help on this.

**Comment by thierryvolpiatto** [comment]
But still think you should reverse the order of options, which do not fail with e.g "-w" added to 
`migemo-options`.
